version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: ./mvnw -Dmaven.test.skip=true package
      - run:
         name: Analyze on SonarCloud
         command: mvn verify sonar:sonar
      - persist_to_workspace:
         root: ./
         paths:
           - target/
      - setup_remote_docker:
          version: 19.03.13

      # build and push Docker image
      - run: |
          TAG=1.0.$CIRCLE_BUILD_NUM
          docker build -t $DOCKERHUB_USERNAME/devsecopsdemo:$TAG .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push $DOCKERHUB_USERNAME/devsecopsdemo:$TAG
workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
